import DLCore
import DLModels
import Foundation
import Testing

/// 合同测试：逐条跑仓库根 `testdata/context-injection-cases.json`，
/// 断言 `kind` 缺失时 DLCore 的文本兜底判定与用例的 `injection` 期望一致。
/// 规则与 Android `ContextInjection.kt`、插件 `src/context-injection.js` 三端对齐。
struct ContextInjectionContractTests {
    private struct InjectionCase: Decodable {
        var name: String
        var injection: Bool
        var text: String
    }

    @Test func sharedCasesMatchThePlugin() throws {
        let cases = try decodeSharedCases()
        #expect(cases.count >= 10, "用例清单太短，可能没读到文件")
        for item in cases {
            #expect(
                isContextInjectionText(item.text) == item.injection,
                "case \(item.name): 兜底判定应与 \(item.injection) 一致"
            )
        }
    }

    @Test func goalRoundTextIsAnInjectionSubtype() throws {
        let text = """
            <goal_round>
            Objective: "ship it"
            Round: 1/256

            Continue working toward the objective in this same session.
            """
        #expect(isContextInjectionText(text))
        #expect(isGoalRoundText(text))
        #expect(goalRoundObjective(text) == "ship it")
        #expect(goalRoundProgress(text) == "1/256")
        #expect(goalRoundObjective("普通消息") == nil)
        #expect(goalRoundProgress("<goal_round>Objective: \"x\"</goal_round>") == nil)
    }

    @Test func modelChangedNoticeIsRecognized() {
        #expect(isModelChangedNotice("[model changed: assistant turns above were generated by deepseek-v4-pro]"))
        #expect(!isModelChangedNotice("为什么提示 model changed？"))
        #expect(
            modelChangedFrom(
                "[model changed: assistant turns above this point were generated by deepseek-v4-pro]")
                == "deepseek-v4-pro"
        )
    }

    @Test func resolvedMessageKindPrefersExplicitKind() {
        #expect(
            resolvedMessageKind(role: "user", kind: "injection", text: "随便什么正文") == .injection
        )
        #expect(
            resolvedMessageKind(role: "context_injection", kind: "goal_round", text: "随便什么正文") == .goalRound
        )
    }

    @Test func resolvedMessageKindFallsBackToTextHeuristics() {
        let reminder = "<system-reminder>\nThe available skill catalog changed.\n</system-reminder>"
        #expect(resolvedMessageKind(role: "user", kind: nil, text: reminder) == .injection)
        let goal = "<goal_round>\nObjective: \"ship it\"\nRound: 1/256\n</goal_round>"
        #expect(resolvedMessageKind(role: "user", kind: nil, text: goal) == .goalRound)
        let notice = "[model changed: assistant turns above this point were generated by deepseek-v4-pro]"
        #expect(resolvedMessageKind(role: "user", kind: nil, text: notice) == .modelChanged)
        #expect(resolvedMessageKind(role: "system_notice", kind: nil, text: "") == .modelChanged)
        #expect(resolvedMessageKind(role: "context_injection", kind: nil, text: "你好") == .injection)
        #expect(resolvedMessageKind(role: "assistant", kind: nil, text: "你好") == .role("assistant"))
        #expect(resolvedMessageKind(role: "user", kind: nil, text: "你好") == .user)
    }

    @Test func injectionLabelsFallBackToWorkspace() {
        #expect(contextInjectionLabels("Current runtime context:\n- cwd: /tmp") == ["runtime"])
        #expect(
            contextInjectionLabels("<system-reminder>\nInstructions from: CLAUDE.md\n</system-reminder>")
                == ["CLAUDE.md"]
        )
        #expect(
            contextInjectionLabels("The available skill catalog changed.\nCurrent DSH file policy: read-only")
                == ["skill-catalog", "file-policy"]
        )
        #expect(contextInjectionLabels("没有标记的正文") == ["workspace"])
    }

    private func decodeSharedCases() throws -> [InjectionCase] {
        struct CaseList: Decodable {
            var cases: [InjectionCase]
        }
        let url = repoRoot()
            .appendingPathComponent("testdata")
            .appendingPathComponent("context-injection-cases.json")
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(CaseList.self, from: data).cases
    }

    private func repoRoot() -> URL {
        // …/apps/ios/Tests/Contract/<file>.swift 逐级上溯 5 层到仓库根
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
    }
}
