import DLModels
import Foundation

/// 识别 DSH 注入到会话里的上下文快照，与插件 `src/context-injection.js`、
/// Android `ContextInjection.kt` 对齐。只认结构性标记，以及以 runtime context /
/// file policy 开头的整段文本；正文里提到 CLAUDE.md、AGENTS.md 或 "Instructions from:" 不算注入。
///
/// 这套兜底只在消息 `kind` 缺失（旧插件、实时流原始事件）时使用；`kind` 在场时以 `kind` 为准。
private func isBlank(_ text: String) -> Bool {
    text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
}

private func containsIgnoringCase(_ text: String, _ needle: String) -> Bool {
    text.lowercased().contains(needle.lowercased())
}

/// `^\s*Current runtime context` / `^\s*Current DSH file policy`（忽略大小写）。
private func hasAnchoredPreface(_ text: String, _ preface: String) -> Bool {
    text.drop(while: { $0.isWhitespace }).lowercased().hasPrefix(preface.lowercased())
}

public func isContextInjectionText(_ text: String) -> Bool {
    if isBlank(text) { return false }
    if isGoalRoundText(text) { return true }
    if containsIgnoringCase(text, "<system-reminder>")
        || containsIgnoringCase(text, "&lt;system-reminder&gt;")
        || containsIgnoringCase(text, "<available_skills>")
        || containsIgnoringCase(text, "&lt;available_skills&gt;")
    {
        return true
    }
    return hasAnchoredPreface(text, "Current runtime context")
        || hasAnchoredPreface(text, "Current DSH file policy")
}

/// goal 模式每轮注入的续跑提示（`<goal_round>` 包装的系统指令）。
/// 这类消息不是用户亲手输入，应折叠为「目标轮次」行而不是铺满整屏的用户气泡。
public func isGoalRoundText(_ text: String) -> Bool {
    !isBlank(text)
        && (containsIgnoringCase(text, "<goal_round>") || containsIgnoringCase(text, "&lt;goal_round&gt;"))
}

/// 从 goal_round 提示里提取 Objective 原文（用户真正设定的目标）；取不到返回 nil。
public func goalRoundObjective(_ text: String) -> String? {
    guard let match = text.firstMatch(of: /Objective:\s*"(.*)"/) else { return nil }
    let value = String(match.1).trimmingCharacters(in: .whitespacesAndNewlines)
    return value.isEmpty ? nil : value
}

/// 从 goal_round 提示里提取轮次（如 "1/256"）；取不到返回 nil。
public func goalRoundProgress(_ text: String) -> String? {
    guard let match = text.firstMatch(of: /Round:\s*([0-9]+\s*\/\s*[0-9]+)/) else { return nil }
    return match.1.replacingOccurrences(of: " ", with: "")
}

/// 注入来源标签（与插件 `contextInjectionLabels` 一致），保序去重；
/// 一个标记都没有时回落 `["workspace"]`。
public func contextInjectionLabels(_ text: String) -> [String] {
    var labels: [String] = []
    func add(_ label: String) {
        if !labels.contains(label) { labels.append(label) }
    }
    if containsIgnoringCase(text, "available_skills")
        || containsIgnoringCase(text, "skill catalog")
        || containsIgnoringCase(text, "available-skills")
    {
        add("skill-catalog")
    }
    if containsIgnoringCase(text, "Current runtime context") { add("runtime") }
    if containsIgnoringCase(text, "Current DSH file policy") { add("file-policy") }
    if containsIgnoringCase(text, "Approval prompts are disabled") { add("approval-policy") }
    for match in text.matches(of: /Instructions from:\s*(.+)/) {
        let name = String(match.1).trimmingCharacters(in: .whitespacesAndNewlines)
        if !name.isEmpty { add(name) }
    }
    for match in text.matches(of: /(?:AGENTS\.md|CLAUDE\.md|\.zcode\/[^\s,]+)/) {
        add(String(match.0))
    }
    return labels.isEmpty ? ["workspace"] : labels
}

/// DSH 在会话中途换模型时插入的提示（`[model changed: …]`）。它挂在 user/message 里，
/// 但不是用户说的话——按用户气泡渲染会让人以为用户交代过这件事。
public func isModelChangedNotice(_ text: String) -> Bool {
    text.trimmingCharacters(in: .whitespacesAndNewlines)
        .lowercased()
        .hasPrefix("[model changed:")
}

/// 从 `[model changed: … generated by <model>]` 中取出模型名；取不到返回 nil。
public func modelChangedFrom(_ text: String) -> String? {
    guard let match = text.firstMatch(of: /generated by\s+([^\]\s]+)/.ignoresCase()) else { return nil }
    let value = String(match.1).trimmingCharacters(in: .whitespacesAndNewlines)
    return value.isEmpty ? nil : value
}

/// 消息的展示类别：优先用插件下发的 `kind`；kind 缺失（旧插件、实时流）时才按 role / 文本兜底。
/// 返回 injection / goal_round / model_changed / user，或原 role（`.role(_)`）。
public func resolvedMessageKind(role: String, kind: String?, text: String) -> MessageKind {
    if let kind, !kind.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
        return MessageKind.decoding(kind)
    }
    if role == "context_injection" || isContextInjectionText(text) {
        return isGoalRoundText(text) ? .goalRound : .injection
    }
    if role == "system_notice" || isModelChangedNotice(text) {
        return .modelChanged
    }
    return MessageKind.decoding(role)
}
