package dev.deeplinks.native.util

import org.junit.Assert.assertEquals
import org.junit.Test

class ResolvedMessageKindTest {
    @Test
    fun pluginKindWins() {
        // 插件说是 user，就算文本看起来像注入也按 user 渲染
        assertEquals("user", resolvedMessageKind("user", "user", "<system-reminder>x</system-reminder>"))
        assertEquals(MessageKind.INJECTION, resolvedMessageKind("context_injection", "injection", "随便"))
        assertEquals(MessageKind.GOAL_ROUND, resolvedMessageKind("context_injection", "goal_round", ""))
    }

    @Test
    fun legacyFallbackWhenKindMissing() {
        assertEquals(MessageKind.INJECTION, resolvedMessageKind("user", null, "<system-reminder>x</system-reminder>"))
        assertEquals(
            MessageKind.GOAL_ROUND,
            resolvedMessageKind("context_injection", null, "<goal_round>\nRound: 1/256\n</goal_round>"),
        )
        assertEquals(
            MessageKind.MODEL_CHANGED,
            resolvedMessageKind("user", null, "[model changed: assistant turns above this point were generated by x]"),
        )
        assertEquals("user", resolvedMessageKind("user", null, "帮我改一下 CLAUDE.md"))
        assertEquals("assistant", resolvedMessageKind("assistant", null, "hi"))
        assertEquals("user", resolvedMessageKind("user", "", "hi"))
    }
}
