package dev.deeplinks.native.util

/**
 * 识别 DSH 注入到会话里的上下文快照，与插件 `src/context-injection.js` 对齐。
 * 只认结构性标记，以及以 runtime context / file policy 开头的整段文本。
 * 正文里提到 CLAUDE.md、AGENTS.md 或 “Instructions from:” 不算注入。
 */
fun isContextInjectionText(text: String): Boolean {
    if (text.isBlank()) return false
    return isGoalRoundText(text) ||
        text.contains("<system-reminder>", ignoreCase = true) ||
        text.contains("&lt;system-reminder&gt;", ignoreCase = true) ||
        text.contains("<available_skills>", ignoreCase = true) ||
        text.contains("&lt;available_skills&gt;", ignoreCase = true) ||
        anchoredRuntimePreface.containsMatchIn(text) ||
        anchoredFilePolicyPreface.containsMatchIn(text)
}

private val anchoredRuntimePreface = Regex("""(?i)^\s*Current runtime context""")
private val anchoredFilePolicyPreface = Regex("""(?i)^\s*Current DSH file policy""")

/**
 * 识别 goal 模式每轮注入的续跑提示（`<goal_round>` 包装的系统指令）。
 * 这类消息不是用户亲手输入，应折叠为「目标轮次」行而不是铺满整屏的用户气泡。
 */
fun isGoalRoundText(text: String): Boolean =
    text.contains("<goal_round>", ignoreCase = true) ||
        text.contains("&lt;goal_round&gt;", ignoreCase = true)

/** 从 goal_round 提示里提取 Objective 原文（用户真正设定的目标）。 */
fun goalRoundObjective(text: String): String? {
    val match = Regex("""Objective:\s*"(.*)"""").find(text) ?: return null
    return match.groupValues[1].trim().takeIf { it.isNotEmpty() }
}

/** 从 goal_round 提示里提取轮次（如 "1/256"）。 */
fun goalRoundProgress(text: String): String? {
    val match = Regex("""Round:\s*([0-9]+\s*/\s*[0-9]+)""").find(text) ?: return null
    return match.groupValues[1].replace(" ", "")
}

/** 注入来源标签，Web 端用「skill-catalog」这种短名。 */
fun contextInjectionLabels(text: String): List<String> {
    val labels = linkedSetOf<String>()
    if (
        text.contains("available_skills", ignoreCase = true) ||
        text.contains("skill catalog", ignoreCase = true) ||
        text.contains("available-skills", ignoreCase = true)
    ) {
        labels.add("skill-catalog")
    }
    if (text.contains("Current runtime context", ignoreCase = true)) {
        labels.add("runtime")
    }
    if (text.contains("Current DSH file policy", ignoreCase = true)) {
        labels.add("file-policy")
    }
    if (text.contains("Approval prompts are disabled", ignoreCase = true)) {
        labels.add("approval-policy")
    }
    Regex("""Instructions from:\s*(.+)""").findAll(text).forEach { match ->
        val name = match.groupValues[1].trim()
        if (name.isNotEmpty()) labels.add(name)
    }
    Regex("""(?:AGENTS\.md|CLAUDE\.md|\.zcode/[^\s,]+)""").findAll(text).forEach { match ->
        labels.add(match.value)
    }
    return labels.toList().ifEmpty { listOf("workspace") }
}

/**
 * DSH 在会话中途换模型时插入的提示（`[model changed: …]`）。它挂在 user/message 里，
 * 但**不是用户说的话**——按用户气泡渲染，会让人以为用户交代过这件事。
 * 与插件 `src/context-injection.js` 的 isModelChangedNotice 规则对齐。
 */
fun isModelChangedNotice(text: String): Boolean =
    text.trim().startsWith("[model changed:", ignoreCase = true)

/**
 * 从 `[model changed: … generated by <model>]` 中取出模型名；取不到返回 null。
 *
 * 取到后由 UI 渲染成「以上回复由 <model> 生成」，不再把 DSH 注入的英文系统文本
 * 原样铺给用户（E2：ChatPageLightZh 里那行灰字）。
 */
fun modelChangedFrom(text: String): String? {
    val m = Regex("""generated by\s+([^\]\s]+)""", RegexOption.IGNORE_CASE).find(text) ?: return null
    return m.groupValues[1].trim().takeIf { it.isNotEmpty() }
}

/** 消息展示类别常量（与插件 history `kind` 对齐）。 */
object MessageKind {
    const val INJECTION = "injection"
    const val GOAL_ROUND = "goal_round"
    const val MODEL_CHANGED = "model_changed"
}

/**
 * 消息的展示类别：优先用插件下发的 kind；kind 缺失（旧插件、实时流）时才按 role / 文本兜底。
 * 返回 injection / goal_round / model_changed，或原 role。
 */
fun resolvedMessageKind(role: String, kind: String?, text: String): String = when {
    !kind.isNullOrBlank() -> kind
    role == "context_injection" || isContextInjectionText(text) ->
        if (isGoalRoundText(text)) MessageKind.GOAL_ROUND else MessageKind.INJECTION
    role == "system_notice" || isModelChangedNotice(text) -> MessageKind.MODEL_CHANGED
    else -> role
}

/** 用户消息的 kind → 旧 role（给仍按 role 判断的旧代码路径）。 */
fun legacyRoleForKind(kind: String): String = when (kind) {
    MessageKind.INJECTION, MessageKind.GOAL_ROUND -> "context_injection"
    MessageKind.MODEL_CHANGED -> "system_notice"
    else -> "user"
}
